CREATE DATABASE IF NOT EXISTS SISTEMA_FORTES;
USE SISTEMA_FORTES;

CREATE TABLE IF NOT EXISTS FUNCIONARIOS_FORTES(
ID_FUNCIONARIO INT PRIMARY KEY,
CPF VARCHAR(11) NOT NULL,
NOME VARCHAR(45) NOT NULL,
EMAIL VARCHAR(45) NOT NULL,
DATA_NASC DATE NOT NULL,
CARGO VARCHAR(25) NOT NULL,
USUARIO VARCHAR(45) NOT NULL,
SENHA VARCHAR(45) NOT NULL
);

CREATE TABLE IF NOT EXISTS INSTITUICOES_CARENTES(
CNPJ_INSTITUICAO VARCHAR(14) PRIMARY KEY,
RAZAO_SOCIAL VARCHAR(45) NOT NULL,
UF CHAR(2) NOT NULL,
CIDADE VARCHAR(45) NOT NULL,
LOGRADOURO VARCHAR(45) NOT NULL,
BAIRRO VARCHAR(45) NOT NULL,
EMAIL VARCHAR(45) NOT NULL,
TELEFONE VARCHAR(45) NOT NULL,
PUBLICO_ALVO VARCHAR(45) NOT NULL
);

CREATE TABLE IF NOT EXISTS FUNCIONARIOS_INSTITUICOES(
CPF_FUNCIONARIO VARCHAR(11) PRIMARY KEY,
CARGO ENUM("Responsável", "Técnico") NOT NULL,
NOME_FUNCIONARIO VARCHAR(45) NOT NULL,
TELEFONE_FUNCIONARIO VARCHAR(45) NOT NULL,
INST_CNPJ VARCHAR(14) NOT NULL,
CONSTRAINT INST_RESP FOREIGN KEY (INST_CNPJ)
REFERENCES INSTITUICOES_CARENTES(CNPJ_INSTITUICAO)
);

CREATE TABLE IF NOT EXISTS REUNIOES(
ID_REUNIAO INT PRIMARY KEY,
DATA_REUNIAO DATE,
HORA_REUNIAO TIME,
TIPO VARCHAR(45) NOT NULL,
DESCRICAO TEXT NOT NULL,
FUNC_ID INT NOT NULL,
INST_CNPJ VARCHAR(14) NOT NULL,
CONSTRAINT FUNC_REUN FOREIGN KEY (FUNC_ID)
REFERENCES FUNCIONARIOS_FORTES (ID_FUNCIONARIO),
CONSTRAINT INST_REUN FOREIGN KEY (INST_CNPJ)
REFERENCES INSTITUICOES_CARENTES (CNPJ_INSTITUICAO)
);

CREATE TABLE IF NOT EXISTS PROJETOS(
ID_PROJETO INT PRIMARY KEY,
NOME VARCHAR(45) NOT NULL,
DATA_INICIO DATE NOT NULL,
PRAZO_CONCLUSAO DATE NOT NULL,
DATA_CONCLUSAO DATE NOT NULL,
DESCRICAO_PROJETO TEXT NOT NULL,
DESCRICAO_CUSTO TEXT NOT NULL,
CUSTO_PREVISTO DECIMAL(10,2) NOT NULL,
GASTO_REALIZADO DECIMAL(10,2) NOT NULL,
INST_CNPJ VARCHAR(14) NOT NULL,
CONSTRAINT INST_PROJ FOREIGN KEY (INST_CNPJ)
REFERENCES INSTITUICOES_CARENTES (CNPJ_INSTITUICAO)
);

CREATE TABLE IF NOT EXISTS EDITAIS(
ID_EDITAL INT PRIMARY KEY,
NOME VARCHAR(45) NOT NULL,
ORCAMENTO DECIMAL(10,2) NOT NULL,
ODS VARCHAR(45) NOT NULL,
DATA_ABERTURA DATE NOT NULL,
DATA_ENCERRAMENTO DATE NOT NULL,
LIMITE_INSCRICOES INT NOT NULL,
AREA_ACAO VARCHAR(45) NOT NULL,
MARCADOR VARCHAR(45) NOT NULL,
ANEXO BLOB NOT NULL,
PROJ_ID INT NOT NULL,
FUNC_ID INT NOT NULL,
CONSTRAINT PROJ_EDI FOREIGN KEY (PROJ_ID)
REFERENCES PROJETOS (ID_PROJETO),
CONSTRAINT FUNC_EDI FOREIGN KEY (FUNC_ID)
REFERENCES FUNCIONARIOS_FORTES(ID_FUNCIONARIO)
);

CREATE TABLE IF NOT EXISTS ATIVIDADES(
ID_ATIVIDADE INT PRIMARY KEY,
NOME VARCHAR(45) NOT NULL,
STATUS_PROGRESSO ENUM("Pendente", "Em andamento", "Finalizado", "Cancelado") NOT NULL,
DESCRICAO TEXT NOT NULL,
DATA_INICIO DATE NOT NULL,
DATA_CONCLUSAO DATE NOT NULL,
DESCRICAO_GASTO TEXT NOT NULL,
CUSTO_APROXIMADO DECIMAL(10,2) NOT NULL,
GASTO_REALIZADO DECIMAL(10,2) NOT NULL,
PROJ_ID INT NOT NULL,
CONSTRAINT PROJ_ATV FOREIGN KEY (PROJ_ID)
REFERENCES PROJETOS (ID_PROJETO)
);

CREATE TABLE IF NOT EXISTS PARCERIAS(
ID_PARCERIA INT PRIMARY KEY,
NOME VARCHAR(45) NOT NULL,
CNPJ VARCHAR(14) NOT NULL,
UF CHAR(2) NOT NULL,
CIDADE VARCHAR(45) NOT NULL,
LOGRADOURO VARCHAR(45) NOT NULL,
BAIRRO VARCHAR(45) NOT NULL
);

CREATE TABLE IF NOT EXISTS PARCERIAS_INSTITUICOES(
PARC_ID INT,
INST_CNPJ VARCHAR(14),
PRIMARY KEY (PARC_ID, INST_CNPJ),
CONSTRAINT PI1 FOREIGN KEY (PARC_ID) 
REFERENCES PARCERIAS(ID_PARCERIA),
CONSTRAINT PI2 FOREIGN KEY (INST_CNPJ) 
REFERENCES INSTITUICOES_CARENTES(CNPJ_INSTITUICAO)
);